# Generated by Django 4.0 on 2021-12-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_rename_content_fruit_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
