# Generated by Django 4.0 on 2021-12-14 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0003_alter_fruit_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fruit',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
